version: "3.9"

services:
  app:
    build: ./build
    restart: always
    command: bash
    tty: true
    stdin_open: true
    environment:
    - NODE_ENV=development
    - MONGO_URL=mongodb://mongo:27017
    - REDIS_URL=redis://redis:6379
    - NTFY_URL=http://51.77.223.186:3000
    env_file:
    - .env.app
    networks:
    - cache
    - db
    ports:
    - "2100:3000"
    volumes:
    - ./app:/app
  
  redis:
    image: redis:latest
    restart: always
    networks:
    - cache
  
  mongo:
    image: mongo:latest
    restart: always
    networks:
    - db
    volumes:
    - db-data:/data/db


networks:
  cache:
  db:


volumes:
  db-data:
